import { Glob } from "bun";

const WARNING_COMMENT =
	"// !!! CODEGEN FILE !!!\n" +
	"// This file is automatically generated by codegen.ts - do not edit manually\n" +
	"\n" +
	"// @ts-nocheck: code-gen file\n" +
	"// biome-ignore-all format\n";

async function generateAssetsFile() {
	console.log("Scanning for asset files...");
	const assetFiles = Array.from(new Glob("**/*").scanSync({ cwd: "./assets", dot: true }))
		.map(p => p.replaceAll("\\", "/"))
		.sort();

	console.log(`Found x${assetFiles.length} asset files`);

	const imports: string[] = [];
	const entries: string[] = [];

	console.log("Generating asset file...");

	assetFiles.forEach((rel, i) => {
		const id = `_a${i}`;
		imports.push(
			`import ${id} from ${JSON.stringify(`../../assets/${rel}`)} with { type: "file" };`
		);
		entries.push(`\t${JSON.stringify(rel)}: ${id},`);
	});

	const file = [
		WARNING_COMMENT,
		imports.join("\n"),
		"",
		"export const assets = {",
		`${entries.join("\n")}`,
		"} as const;",
		"",
		"export type AssetName = keyof typeof assets;",
		"",
		"export function asset(name: AssetName): string {",
		"\treturn assets[name];",
		"}"
	].join("\n");

	await Bun.write("./src/codegen/assets.codegen.ts", file.replace(/\r\n/g, "\n"));

	console.log("Finished generating asset file");
}

console.log("Starting code generation...");

await generateAssetsFile();

console.log("Finished code generation");
